### ISSUE TITLE
Cant Install (Node via Homebrew)

### ISSUE THREAD

**Issue by OwenMelbz** [dbankier/TiShadow#421]
Every time I try and install it I get a fail on the postinstall section.

Here is the terminal dump
```
MacMini:~ Apps$ npm install -g dbankier/TiShadow
npm WARN engine tishadow@2.8.1: wanted: {"node":"0.10.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
|
> ws@0.4.32 install /usr/local/lib/node_modules/tishadow/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> ws@0.4.32 install /usr/local/lib/node_modules/tishadow/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
/usr/local/bin/ts -> /usr/local/lib/node_modules/tishadow/cli/tishadow
/usr/local/bin/tishadow -> /usr/local/lib/node_modules/tishadow/cli/tishadow

> tishadow@2.8.1 postinstall /usr/local/lib/node_modules/tishadow
> node cli/tishadow express

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn ti ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickDomainCallback (node.js:381:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "dbankier/TiShadow"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! tishadow@2.8.1 postinstall: `node cli/tishadow express`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tishadow@2.8.1 postinstall script 'node cli/tishadow express'.
npm ERR! This is most likely a problem with the tishadow package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node cli/tishadow express
npm ERR! You can get their info via:
npm ERR!     npm owner ls tishadow
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Apps/npm-debug.log
MacMini:~ Apps$
```

OSX 10.10.2

**Comment by shodanuk** [comment]
The output is telling you problem in the first line:

    npm WARN engine tishadow@2.8.1: wanted: {"node":"0.10.x"} (current: {"node":"0.12.0","npm":"2.5.1"}

I don't believe Node.js 0.12.x is supported. You'll need Node.js 0.10.x.

Check out NVM (can be installed via Homebrew) for easily installing & managing multiple versions of Node.

**Comment by OwenMelbz** [comment]
We'll even with node 0.10 its still failing on the same file.

```
MacMini:~ Apps$ nvm install 0.10
######################################################################## 100.0%
Now using node v0.10.37
MacMini:~ Apps$ nvm use 0.10
Now using node v0.10.37
MacMini:~ Apps$ npm install -g tishadow
 
> ws@0.4.32 install /Users/Apps/.nvm/v0.10.37/lib/node_modules/tishadow/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> ws@0.4.32 install /Users/Apps/.nvm/v0.10.37/lib/node_modules/tishadow/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
/Users/Apps/.nvm/v0.10.37/bin/tishadow -> /Users/Apps/.nvm/v0.10.37/lib/node_modules/tishadow/cli/tishadow
/Users/Apps/.nvm/v0.10.37/bin/ts -> /Users/Apps/.nvm/v0.10.37/lib/node_modules/tishadow/cli/tishadow

> tishadow@2.8.1 postinstall /Users/Apps/.nvm/v0.10.37/lib/node_modules/tishadow
> node cli/tishadow express


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

npm ERR! tishadow@2.8.1 postinstall: `node cli/tishadow express`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the tishadow@2.8.1 postinstall script.
npm ERR! This is most likely a problem with the tishadow package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node cli/tishadow express
npm ERR! You can get their info via:
npm ERR!     npm owner ls tishadow
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.1.0
npm ERR! command "/Users/Apps/.nvm/v0.10.37/bin/node" "/Users/Apps/.nvm/v0.10.37/bin/npm" "install" "-g" "tishadow"
npm ERR! cwd /Users/Apps
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by shodanuk** [comment]
Hmm... does the latest npm bundle so the same thing? ie `npm i tishadow -g`

**Comment by OwenMelbz** [comment]
running `npm i tishadow -g` installed fine thank you!

**Comment by shodanuk** [comment]
No probs :)

**Comment by dbankier** [comment]
Looks like the post install error when installed via brew is because you need to use the `--unsafe-perm` when installing with `sudo`. You don't need `sudo` or the flag when using nvm.
