### ISSUE TITLE
Not working with Ti SDK 4.1.1.GA?

### ISSUE THREAD

**Issue by bitfabrikken** [dbankier/TiShadow#452]
Getting the following error when trying to run on a device - it's a fresh install of the tishadow app via "tishadow app -d tishadow" - how to fix?

```
[ERROR] :  AndroidRuntime: FATAL EXCEPTION: main
[ERROR] :  AndroidRuntime: Process: dk.bitfabrikken.tishadowapp, PID: 6893
[ERROR] :  AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{dk.bitfabrikken.tishadowapp/org.appcelerator.titanium.TiActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features
[ERROR] :  AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2694)
[ERROR] :  AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2761)
[ERROR] :  AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:178)
[ERROR] :  AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
[ERROR] :  AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  AndroidRuntime: 	at android.os.Looper.loop(Looper.java:145)
[ERROR] :  AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5946)
[ERROR] :  AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
[ERROR] :  AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
[ERROR] :  AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
[ERROR] :  AndroidRuntime: Caused by: java.lang.IllegalArgumentException: AppCompat does not support the current theme features
[ERROR] :  AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:360)
[ERROR] :  AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:237)
[ERROR] :  AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:111)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:562)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
[ERROR] :  AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6289)
[ERROR] :  AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
[ERROR] :  AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
[ERROR] :  AndroidRuntime: 	... 10 more
```

**Comment by shodanuk** [comment]
I experienced this recently too. Looks like an incompatibility with something to do with Android themes in the 4.1.1.GA SDK.

Falling back to the 4.0.0.GA SDK fixed this for me as I didn't specifically need anything from 4.1.1.GA.

**Comment by skypanther** [comment]
I skipped over the 4.x SDK versions as they were pretty buggy for me. TiShadow is working for me with 5.0.0.GA. Though, I use a different technique: in the project directory `ti build -p <platform> -T device --shadow`

**Comment by dbankier** [comment]
not sure what caused it, but it worked fine on 5.0.0.GA. I tweaked the theming which might fix your 4.X issues.
