### ISSUE TITLE
Config Error on line 105 throws TypeError: undefined is not a function: config.isAlloy1_8_later = config.isAlloy && spawnSync("alloy",["-v"]).stdo

### ISSUE THREAD

**Issue by claytongray** [dbankier/TiShadow#493]
Here's the terminal ouput:

```
ts run

/usr/local/lib/node_modules/tishadow/cli/support/config.js:105
    config.isAlloy1_8_later = config.isAlloy && spawnSync("alloy",["-v"]).stdo
                                                ^
TypeError: undefined is not a function
    at /usr/local/lib/node_modules/tishadow/cli/support/config.js:105:49
    at /usr/local/lib/node_modules/tishadow/cli/support/config.js:54:5
    at /usr/local/lib/node_modules/tishadow/node_modules/tiapp/lib/tiapp.js:18:15
    at Parser.<anonymous> (/usr/local/lib/node_modules/tishadow/node_modules/tiapp/node_modules/xml2js/lib/xml2js.js:255:20)
    at Parser.emit (events.js:95:17)
    at Object.saxParser.onclosetag (/usr/local/lib/node_modules/tishadow/node_modules/tiapp/node_modules/xml2js/lib/xml2js.js:225:24)
    at emit (/usr/local/lib/node_modules/tishadow/node_modules/tiapp/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/usr/local/lib/node_modules/tishadow/node_modules/tiapp/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/usr/local/lib/node_modules/tishadow/node_modules/tiapp/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
    at Object.write (/usr/local/lib/node_modules/tishadow/node_modules/tiapp/node_modules/xml2js/node_modules/sax/lib/sax.js:1293:29)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/tishadow/node_modules/tiapp/node_modules/xml2js/lib/xml2js.js:273:29)

```

Here's the line in config.js, line 105:
`config.isAlloy1_8_later = config.isAlloy && spawnSync("alloy",["-v"]).stdout >= "1.8.0";`

If I change that line to below, it works fine.
`config.isAlloy1_8_later = "1.8.0";`

I have spawnSync installed, just updated it, too.

**Comment by dbankier** [comment]
Is alloy installed?

**Comment by dbankier** [comment]
closing - no activity.
