### ISSUE TITLE
how install tishadow on macOS Sierra

### ISSUE THREAD

**Issue by furthurr** [dbankier/TiShadow#502]
I can not install tishadow on Mac OS Sierra ... please help 

```
/usr/local/lib/node_modules/tishadow/cli/tishadow:256
    .on('ready', ()=> {
                  ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Darwin 16.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "dbankier/TiShadow" "--unsafe-perm"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! tishadow@2.8.8 postinstall: `node cli/tishadow express`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tishadow@2.8.8 postinstall script 'node cli/tishadow express'.
npm ERR! This is most likely a problem with the tishadow package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node cli/tishadow express
npm ERR! You can get their info via:
npm ERR!     npm owner ls tishadow
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pedrogomezvasquez/npm-debug.log
```

**Comment by dbankier** [comment]
what version of node are you running?

**Comment by furthurr** [comment]
node v0.12.7

**Comment by dbankier** [comment]
that would explain it... some of the js needs a minimum of 4.

**Comment by furthurr** [comment]
what i need to do?

**Comment by dbankier** [comment]
do you need to be on 0.12?

**Comment by furthurr** [comment]
i downloaded the version 4.0.5 of https://nodejs.org/en/download/
Now tiShadow is working the @dbankier

**Comment by dbankier** [comment]
Great
