### ISSUE TITLE
Windows 7 installation

### ISSUE THREAD

**Issue by AlessandroSangiuliano** [dbankier/TiShadow#505]
Hello.

When I try to install tishadow with npm on Windows 7 I get this:

> ws@0.4.32 install C:\Users\Alex\AppData\Roaming\npm\node_modules\tishadow\nod
ient\node_modules\ws                                                           
> (node-gyp rebuild 2> builderror.log) || (exit 0)                             
                                                                               
                                                                               
C:\Users\Alex\AppData\Roaming\npm\node_modules\tishadow\node_modules\socket.io\
>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_m
es\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )                  
/                                                                              
> ws@0.4.32 install C:\Users\Alex\AppData\Roaming\npm\node_modules\tishadow\nod
> (node-gyp rebuild 2> builderror.log) || (exit 0)                             
                                                                               
                                                                               
C:\Users\Alex\AppData\Roaming\npm\node_modules\tishadow\node_modules\socket.io-
fig_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp
p.js" rebuild )  else (node  rebuild )                                         
C:\Users\Alex\AppData\Roaming\npm\tishadow -> C:\Users\Alex\AppData\Roaming\npm
C:\Users\Alex\AppData\Roaming\npm\ts -> C:\Users\Alex\AppData\Roaming\npm\node_
                                                                               
> tishadow@2.8.8 postinstall C:\Users\Alex\AppData\Roaming\npm\node_modules\tis
> node cli/tishadow express                                                    
                                                                               
C:\Users\Alex\AppData\Roaming\npm\node_modules\tishadow\cli\tishadow:256       
    .on('ready', ()=> {                                                        
                  ^                                                            
SyntaxError: Unexpected token )                                                
    at exports.runInThisContext (vm.js:73:16)                                  
    at Module._compile (module.js:443:25)                                      
    at Object.Module._extensions..js (module.js:478:10)                        
    at Module.load (module.js:355:32)                                          
    at Function.Module._load (module.js:310:12)                                
    at Function.Module.runMain (module.js:501:10)                              
    at startup (node.js:129:16)                                                
    at node.js:814:3                                                           
npm ERR! Windows_NT 6.1.7601                                                   
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files 
i.js" "install" "-g" "tishadow"                                                
npm ERR! node v0.12.7                                                          
npm ERR! npm  v2.11.3                                                          
npm ERR! code ELIFECYCLE                                                       
                                                                               
npm ERR! tishadow@2.8.8 postinstall: `node cli/tishadow express`               
npm ERR! Exit status 1                                                         
npm ERR!                                                                       
npm ERR! Failed at the tishadow@2.8.8 postinstall script 'node cli/tishadow exp
npm ERR! This is most likely a problem with the tishadow package,              
npm ERR! not with npm itself.                                                  
npm ERR! Tell the author that this fails on your system:                       
npm ERR!     node cli/tishadow express                                         
npm ERR! You can get their info via:                                           
npm ERR!     npm owner ls tishadow                                             
npm ERR! There is likely additional logging output above.                      
                                                                               
npm ERR! Please include the following file with any support request:           
npm ERR!     C:\Users\Alex\npm-debug.log        

Is there something of wrong with my system?

Thank you.

**Comment by dbankier** [comment]
node version?

**Comment by AlessandroSangiuliano** [comment]
it is in the previous output, but however:

C:\Users\Alex
λ node -v
v0.12.7

**Comment by dbankier** [comment]
try at least node 4.

**Comment by AlessandroSangiuliano** [comment]
Ok thank you, I'll try soon. That is the node that comes with Titanium.

**Comment by AlessandroSangiuliano** [comment]
Ok, the installation problem is fixed. Now I have another problem but it seems I'm doing something of wrong with tishadow (first time I'm trying it).

Everything works, now I'm trying on OSX, and followed the hints on the web site for the first test (tishadow app /directory etc etc), it creates a sadowed ap and ask me the connection to the server and in the web page I can see the device (genymotion) connected and working. 

The problem comes with alloy projects. I did read they are supported but if i create the simple Hello World created by Appcelerator Studio and then I do:

1) ti build --platform android --target emulator --device-id "Google Nexus 4 - 5.1.0 - API 22 - "768x1280" --shadow

the app starts to be built, the server is started and it asks me what IP I want to use, the app is deployed and starts to run, but the connection window to the tishadow server is never shown so I can't connect the sadowed app to the server and it just looks like a non shadowed app. In the web page the device results not connected. I investigated a bit and I saw that --shadow flag appify the app creating a app.js (and appyfy.js) with all the necessary code to get connected to the server. I added an alert and I saw that the code is never executed. I know that in alloy (and I'm tryind to get tushadow working with alloy)  the first file executed is index.js instead on titanium is app.js.

What I'm wronging?
