### ISSUE TITLE
Can't use TiShadow 2.8.8

### ISSUE THREAD

**Issue by bitfabrikken** [dbankier/TiShadow#507]
Hi! Just setup a new PC with Titanium, Java, Android SDK, etc. 

But after I install TiShadow with "npm install -g tishadow", I get errors when I try different things.

Windows 10 64 bit, npm 1.3.2,  node 4.6.0

"ts server" error:

``` text
C:\Users\kronholm\AppData\Roaming\npm\node_modules\tishadow\node_modules\update-notifier\index.js:28
                throw new Error('pkg.name and pkg.version required');
                ^

Error: pkg.name and pkg.version required
    at new UpdateNotifier (C:\Users\kronholm\AppData\Roaming\npm\node_modules\tishadow\node_modules\update-notifier\index.js:28:9)
    at module.exports (C:\Users\kronholm\AppData\Roaming\npm\node_modules\tishadow\node_modules\update-notifier\index.js:140:23)
    at Command.<anonymous> (C:\Users\kronholm\AppData\Roaming\npm\node_modules\tishadow\cli\tishadow:45:20)
    at Command.listener (C:\Users\kronholm\AppData\Roaming\npm\node_modules\tishadow\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (C:\Users\kronholm\AppData\Roaming\npm\node_modules\tishadow\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\kronholm\AppData\Roaming\npm\node_modules\tishadow\node_modules\commander\index.js:458:21)
    at execute (C:\Users\kronholm\AppData\Roaming\npm\node_modules\tishadow\cli\tishadow:217:11)
    at Object.<anonymous> (C:\Users\kronholm\AppData\Roaming\npm\node_modules\tishadow\cli\tishadow:264:1)
```

ts app -d ts:

``` text
C:\Users\kronholm\AppData\Roaming\npm\node_modules\tishadow\cli\tishadow:180
      program.prompt("Enter app id [com.yydigital.tishadowapp]: ", function(appid) {
              ^

TypeError: program.prompt is not a function
    at Command.<anonymous> (C:\Users\kronholm\AppData\Roaming\npm\node_modules\tishadow\cli\tishadow:180:15)
    at Command.listener (C:\Users\kronholm\AppData\Roaming\npm\node_modules\tishadow\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (C:\Users\kronholm\AppData\Roaming\npm\node_modules\tishadow\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\kronholm\AppData\Roaming\npm\node_modules\tishadow\node_modules\commander\index.js:458:21)
    at execute (C:\Users\kronholm\AppData\Roaming\npm\node_modules\tishadow\cli\tishadow:217:11)
    at Object.<anonymous> (C:\Users\kronholm\AppData\Roaming\npm\node_modules\tishadow\cli\tishadow:264:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by bitfabrikken** [comment]
Downgrading to 2.8.6 works for me.

**Comment by dbankier** [comment]
Sounds odd. Can you try again with the latest version.

**Comment by bitfabrikken** [comment]
2.9.0 works :)
