### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by michielvaneerd** [dbankier/TiShadow#510]
The installation of TiShadow 2.8.8 fails on my Mac with node 4.6.1 and npm 3.10.9. I used to be able to install it with previous versions without problems, so I'm not sure what's causing this.

This is the output I get:

```
> tishadow@2.8.8 postinstall /Users/michielve/lib/node_modules/tishadow
> node cli/tishadow express

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn ti ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/Users/michielve/bin/npm" "install" "-g" "tishadow"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! tishadow@2.8.8 postinstall: `node cli/tishadow express`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tishadow@2.8.8 postinstall script 'node cli/tishadow express'.
```

**Comment by caspahouzer** [comment]
Did you use "sudo"?

I just updated to the 2.8.8 on my Mac without any problems

**Comment by michielvaneerd** [comment]
Thanks for your suggestion, but I didn't need to do this before as my NPM prefix is set to my home directory.

**Comment by michielvaneerd** [comment]
This is solved by installing the **titanium** cli module (I only had the paid **appcelerator** cli).
