### ISSUE TITLE
npm install fails on new mac

### ISSUE THREAD

**Issue by bitfabrikken** [dbankier/TiShadow#517]
Got a new mac and installed Titanium.
Then went to terminal and typed "sudo npm install -g tishadow"
Here's the output incl. errors:

```
bitfabrikken-mac$ sudo npm install -g tishadow
Password:
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated wrench@1.4.4: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated minimatch@0.0.5: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
 
> ws@0.4.32 install /usr/local/lib/node_modules/tishadow/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> ws@0.4.32 install /usr/local/lib/node_modules/tishadow/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> fsevents@1.0.15 install /usr/local/lib/node_modules/tishadow/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/usr/local/lib/node_modules/tishadow/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
/usr/local/bin/tishadow -> /usr/local/lib/node_modules/tishadow/cli/tishadow
/usr/local/bin/ts -> /usr/local/lib/node_modules/tishadow/cli/tishadow

> tishadow@2.9.0 postinstall /usr/local/lib/node_modules/tishadow
> node cli/tishadow express

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn ti ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "tishadow"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! tishadow@2.9.0 postinstall: `node cli/tishadow express`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tishadow@2.9.0 postinstall script 'node cli/tishadow express'.
npm ERR! This is most likely a problem with the tishadow package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node cli/tishadow express
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tishadow
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls tishadow
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bitfabrikken-mac/npm-debug.log
```

**Comment by bitfabrikken** [comment]
Here's the npm-debug.log: https://gist.github.com/bitfabrikken/a083503c9d6f5b4a0822325216a45316

**Comment by dbankier** [comment]
Try with this `$ sudo npm install -g tishadow --unsafe-perm`

**Comment by pedrotnascimento** [comment]
Same problem to me, tested the suggestion, also failed!(with the 2.8.2 and 2.9.0 versions)

**Comment by pedrotnascimento** [comment]
Solved to me: https://github.com/dbankier/TiShadow/issues/510

> This is solved by installing the titanium cli module (I only had the paid appcelerator cli).

**Comment by bitfabrikken** [comment]
sudo npm install -g titanium 
worked like a charm :)
