### ISSUE TITLE
TiShadow crashes after a few reloads

### ISSUE THREAD

**Issue by jakejdavis** [dbankier/TiShadow#528]
After a certain amount of reloads (usually under 10) TiShadow will crash and return: 
```
[INFO] Beginning Build Process
[INFO] 1 file(s) bundled.
[INFO] Uploading...
C:\Users\jake\AppData\Roaming\npm\node_modules\tishadow\server\routes\index.js:54
    var data = JSON.parse(fields.data[0]),
                                ^

TypeError: Cannot read property 'data' of undefined
    at C:\Users\jake\AppData\Roaming\npm\node_modules\tishadow\server\routes\index.js:54:33
    at C:\Users\jake\AppData\Roaming\npm\node_modules\tishadow\node_modules\multiparty\index.js:116:9
    at C:\Users\jake\AppData\Roaming\npm\node_modules\tishadow\node_modules\multiparty\index.js:108:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
 C:\Users\jake\AppData\Roaming\npm\node_modules\tishadow\node_modules\node-notifier\lib\utils.js:237
    options.m = options.message.replace(/\x1b/g, '');
                                ^

TypeError: options.message.replace is not a function
    at Object.module.exports.mapToWin8 (C:\Users\jake\AppData\Roaming\npm\node_modules\tishadow\node_modules\node-notifier\lib\utils.js:237:33)
    at WindowsToaster.notify (C:\Users\jake\AppData\Roaming\npm\node_modules\tishadow\node_modules\node-notifier\notifiers\toaster.js:60:19)
    at Object.exports.log (C:\Users\jake\AppData\Roaming\npm\node_modules\tishadow\server\logger.js:25:14)
    at Object.exports.(anonymous function) [as error] (C:\Users\jake\AppData\Roaming\npm\node_modules\tishadow\server\logger.js:49:13)
    at ClientRequest.<anonymous> (C:\Users\jake\AppData\Roaming\npm\node_modules\tishadow\cli\support\api.js:43:28)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnEnd (_http_client.js:344:9)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
 [ERROR] TiShadow Server exited.
```

Node v6.3.0
Titanium SDK 6.1.0.v20170401095755 
Windows 10

**Comment by dbankier** [comment]
Confirmed with node >6.0. Just going through the process of updating socket.io and client. Looks like it is solving it. Will push the update after a few more tests...

**Comment by jakejdavis** [comment]
I still sometimes get the error:
```
C:\Users\jake\AppData\Roaming\npm\node_modules\tishadow\server\routes\index.js:54
    var data = JSON.parse(fields.data[0]),
                                ^

TypeError: Cannot read property 'data' of undefined
    at C:\Users\jake\AppData\Roaming\npm\node_modules\tishadow\server\routes\index.js:54:33
    at C:\Users\jake\AppData\Roaming\npm\node_modules\tishadow\node_modules\multiparty\index.js:116:9
    at C:\Users\jake\AppData\Roaming\npm\node_modules\tishadow\node_modules\multiparty\index.js:108:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
 [INFO] Uploading...
[ERROR] Error: socket hang up
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET
[ERROR] TiShadow Server exited.
```
but might not be related to the previous issue.
