### ISSUE TITLE
Can't start tishadow 2.9.2

### ISSUE THREAD

**Issue by Astrovic** [dbankier/TiShadow#534]
Hi, I've this environments:
node v4.6.2
npm 2.15.11

I installed  tishadow 2.9.2 using `sudo npm install -g tishadow --unsafe-perm`.
But when I start server using `ts server` get this error:

```
/usr/local/lib/node_modules/tishadow/server/support/sockets.js:169
      let host = socket.host;
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/tishadow/server/routes/index.js:9:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by furthurr** [comment]
I have the same issue

**Comment by icecandy** [comment]
i have the same problem with latest 2.9.2

**Comment by dbankier** [comment]
Can you use a higher version of node?

**Comment by furthurr** [comment]
Which version is recommended?

**Comment by dbankier** [comment]
6

**Comment by furthurr** [comment]
# Solved

I installed the node version 
v6.11.0
and the TiShadow version 
2.9.2

Thk @dbankier

**Comment by icecandy** [comment]
I just installed node 6.11.1 to try to get this working. Now when I do:
$ sudo npm install -g tishadow
I get:
module.js:471
    throw err;
    ^

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

So this still doesn't work for me,

**Comment by icecandy** [comment]
Well I uninstalled npm and resintalled node 6.11.1 and now tishadow 2.9.2 installs.
What a headache node installation is!

**Comment by chmiiller** [comment]
+1 for the solution. Was using node 4.x before and with 6.x it fixes the issue
@icecandy Yes they are! I got myself on this Today for hours!!
