### ISSUE TITLE
Unable To Install

### ISSUE THREAD

**Issue by joshualambert** [dbankier/TiShadow#560]
Howdy! I'm getting the following error during install. Any ideas what I might be doing wrong?

```> tishadow@2.10.1 postinstall /Users/joshualambert/.nvm/versions/node/v9.0.0/lib/node_modules/tishadow
> node cli/tishadow express

events.js:193
      throw er; // Unhandled 'error' event
      ^

Error: spawn ti ENOENT
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    at Function.Module.runMain (module.js:684:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/tishadow/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tishadow@2.10.1 postinstall: `node cli/tishadow express`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tishadow@2.10.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joshualambert/.npm/_logs/2019-07-14T19_55_06_751Z-debug.log```

**Comment by joshualambert** [comment]
So @ewanharris helped me figure this out. Because I was using the `appc` CLI tool primarily, I didn't have the `titanium` CLI tool instead on its own. It's working now after doing `npm install -g titanium`.
