### ISSUE TITLE
Error during installation of TiShadow

### ISSUE THREAD

**Issue by ferdi2005** [dbankier/TiShadow#562]
Installing TiShadow on (nvm) Node v10.16.3 with NPM 6.9.0 (tried also last version of node).
It returns this error during post-install I think:
```
> tishadow@2.10.1 postinstall /Users/ferdi2005/.nvm/versions/node/v12.10.0/lib/node_modules/tishadow
> node cli/tishadow express

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/ferdi2005/.nvm/versions/node/v12.10.0/lib/node_modules/tishadow/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/ferdi2005/.nvm/versions/node/v12.10.0/lib/node_modules/tishadow/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/ferdi2005/.nvm/versions/node/v12.10.0/lib/node_modules/tishadow/node_modules/configstore/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tishadow@2.10.1 postinstall: `node cli/tishadow express`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tishadow@2.10.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!      /Users/ferdi2005/.npm/_logs/2019-09-24T18_31_27_460Z-debug.log
```

The complete log extracted from  /Users/ferdi2005/.npm/_logs/2019-09-24T18_31_27_460Z-debug.log is [https://gist.github.com/ferdi2005/17bf315096adaa3d48119c3d7e6a1b87](here).

**Comment by dbankier** [comment]
Don't think titanium is working with node 12 yet, so not using ts with it (yet).

**Comment by murilobr** [comment]
I'm having a similar issue.

```> npm install -g dbankier/TiShadow
npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated wrench@1.4.4: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated minimatch@0.0.5: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated mkdirp@0.5.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/Users/murilobr/.nvm/versions/node/v12.18.3/bin/tishadow -> /Users/murilobr/.nvm/versions/node/v12.18.3/lib/node_modules/tishadow/cli/tishadow
/Users/murilobr/.nvm/versions/node/v12.18.3/bin/ts -> /Users/murilobr/.nvm/versions/node/v12.18.3/lib/node_modules/tishadow/cli/tishadow

> fsevents@1.2.13 install /Users/murilobr/.nvm/versions/node/v12.18.3/lib/node_modules/tishadow/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> core-js@2.6.11 postinstall /Users/murilobr/.nvm/versions/node/v12.18.3/lib/node_modules/tishadow/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> tishadow@2.10.2 postinstall /Users/murilobr/.nvm/versions/node/v12.18.3/lib/node_modules/tishadow
> node cli/tishadow express

fs.js:36
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:36:5
    at req_ (/Users/murilobr/.nvm/versions/node/v12.18.3/lib/node_modules/tishadow/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/murilobr/.nvm/versions/node/v12.18.3/lib/node_modules/tishadow/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/murilobr/.nvm/versions/node/v12.18.3/lib/node_modules/tishadow/node_modules/configstore/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tishadow@2.10.2 postinstall: `node cli/tishadow express`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tishadow@2.10.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/murilobr/.npm/_logs/2020-08-28T15_06_35_513Z-debug.log```

**Comment by dbankier** [comment]
Use nvm and drop back to node 10 for the moment.
